### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by wNee** [apache/servicecomb-pack#333]
In mac os when run mvn clean install -e
comes this error: io.fabric8:docker-maven-plugin:0.26.0:build failed: group id '254449427' is too big
Some solution is that: add <tarLongFileMode>posix</tarLongFileMode> in to pom.xml
Does this solution works?
if so, could you provide a pom.xml because I do not know which line to add posix.

Thanks

**Comment by WillemJiang** [comment]
Could you share the stack trace of the issue and the version of docker?
I used the mac OSX to run the build in my daily work, I didn't see this kind of error before.

**Comment by wNee** [comment]
The docker of my mac OSX is Version 17.06.1-ce-mac24 (18936)

**Comment by wNee** [comment]
Here is the trace of issue
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project saga-discovery-servicecenter: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/wnie/workspace/java/servicecomb-saga/saga-discovery/saga-discovery-servicecenter/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project saga-discovery-servicecenter: There are test failures.

Please refer to /Users/wnie/workspace/java/servicecomb-saga/saga-discovery/saga-discovery-servicecenter/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /Users/wnie/workspace/java/servicecomb-saga/saga-discovery/saga-discovery-servicecenter/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:91)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:320)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:892)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by WillemJiang** [comment]
My docker version is

>   Docker version 18.06.1-ce, build e68fc7a

I just pushed a latest Alpha Server docker image to servicecomb/alpha-server:0.3.0-SNAPSHOT，you can try it yourself.

**Comment by wNee** [comment]
Thank you very much. It is really very helpful

**Comment by WillemJiang** [comment]
@wNee Do you consider to upgrade your docker version? Please let me know if the issue is still there.

**Comment by wNee** [comment]
@WillemJiang 
here is my docker version and still have the problem
docker --version
Docker version 18.06.1-ce, build e68fc7a
 
java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
 
mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: US-ASCII
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"

**Comment by WillemJiang** [comment]
It looks your JDK and mvn version are old.
Here is mine.

Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T15:58:13+08:00)
Maven home: /opt/apache-maven-3.5.2
Java version: 1.8.0_172, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre
Default locale: en_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.1", arch: "x86_64", family: "mac"

**Comment by WillemJiang** [comment]
@wNee Did you still have some trouble to build the docker images of Alpha?
I need to close this issue as there is no feedback for a long time, please let me know if you have any other question about it.

**Comment by wNee** [comment]
I have no problems. Thank you




At 2019-03-05 09:15:16, "Willem Jiang" <notifications@github.com> wrote:


@wNee Did you still have some trouble to build the docker images of Alpha?
I need to close this issue as there is no feedback for a long time, please let me know if you have any other question about it.
